# frozen_string_literal: true

source "https://rubygems.org"

gem "capybara", "3.29.0"
gem "cucumber", "4.1.0"
gem "selenium-webdriver", "3.142.7"
gem "rspec", "3.9.0"
gem "ffi", "1.12.2"
gem "site_prism", "3.5"
gem "faker", "2.13.0"
gem "syntax", "1.2.2"



# gem "rails"
